### ISSUE TITLE
Use url param to keep track of whether the user has hidden the expert help suggestion

### ISSUE THREAD

**Issue by tampakis** [upenn-libraries/discovery-app#65]
Currently the expert help box is set to be collapsed on page load and expand on larger screens with this [javascript function](https://github.com/upenn-libraries/discovery-app/blob/master/app/assets/javascripts/expert_help_mobile_hide.js).

When a user chooses to hide the expert box, use javascript to add a url param like `expert=hidden` that can carry over across  the session. When that parameter is present then box should remain collapsed on subsequent search pages. I _think_ Rails just works in terms of preserving the present parameters on subsequent search box submissions. Clicking a facet might be a bit more complicated though since those urls are generated before the page loads.

There might be a better approach to this, the main goal is to accomplish keeping the box collapsed if the user collapses it once. Maybe a session/cookie value would be more robust?

**Comment by mksndz** [comment]
how about a :cookie: ? this would retain the hiding across sessions on the same machine.

or, a value stored in the user's session - which wouldn't persist across sessions but would probably be "stickier" than a URL param.
